---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.13.4
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    configInline:
      peers:
        - peer-address: ${ROUTER_IP}
          peer-asn: ${BGP_PEER_ASN}
          my-asn: ${BGP_PEER_ASN}
      address-pools:
        - name: bgp
          protocol: bgp
          addresses:
            - ${K8S_LB_CIDR}
          avoid-buggy-ips: true
    # prometheusRule:
    #   enabled: true
    # prometheus:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true
    #   prometheusRule:
    #     enabled: true
  # controller:
    #   image:
    #     repository: quay.io/metallb/controller
    #     tag: v0.10.1
    #   tolerations:
    #     - key: "arm"
    #       operator: "Exists"
    # speaker:
    #   image:
    #     repository: quay.io/metallb/speaker
    #     tag: v0.10.1
    #   tolerations:
    #     - key: "arm"
    #       operator: "Exists"
    #     - key: "armhf"
    #       operator: "Exists"
    #     - key: "node-role.kubernetes.io/master"
    #       operator: "Exists"
