---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: home-automation
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zwavejs2mqtt
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: zwavejs/zwavejs2mqtt
      tag: 6.9.1
    env:
      TZ: "${TIMEZONE}"
      NETWORK_KEY: "${SECRET_ZWAVE_KEY}"
    service:
      main:
        ports:
          websocket:
            enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ${SECRET_DOMAIN}
          cert-manager.io/cluster-issuer: letsencrypt-production
          # traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          # nginx.ingress.kubernetes.io/auth-url: https://auth.${DOMAIN}/oauth2/auth
          # nginx.ingress.kubernetes.io/auth-signin: https://auth.${DOMAIN}/oauth2/start
          hajimari.io/enable: "true"
          hajimari.io/icon: z-wave
        hosts:
          - host: zjs2m.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - zjs2m.${SECRET_DOMAIN}
            secretName: zwavejs2mqtt-tls
    persistence:
      config:
        enabled: true
        existingClaim: zwavejs2mqtt-config
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-0658_0200-if00
        mountPath: /dev/zwave-controller
        # hostPathType: CharDevice
        # hostPathType: File
        # hostPath: /dev/serial/by-id/usb-0658_0200-if00
    securityContext:
      privileged: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-zwave
                  operator: In
                  values: ["true"]
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 200Mi
