# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:gsILQCTCyYEtJnY8EXml+bSm9pq5SpORI5fhyWdVeFYb/cNJ5w==,iv:gyKTf8R+LiXCRTNZ+qLz/Kiuf95kTQUfFegJypv9bjI=,tag:3mfEQJKLYSZ/AiHBle21DA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVUlwdGhvbVZIa2ppVmdx
            RyttV3pXOWVpOVo5RmJtaDk5S3VmbXRoTGp3CmpDQVpYNmd3bkw3Y2FjQTd1ME1I
            TU9zY2U5bnk0eG16UnJHcm9xU2NpcDgKLS0tIEowVkFyZmJ0Z2c4VFl4TzEyNXRM
            UklFYmVzbkcyS3RxbmJZMFd6WUZpN00KOKZ5rwyS8nTXvVjAD8FjAoAuuze5cFrO
            BEVgqi4dLQVTn8FbZ4kP8pGdNtJe3Bo1Z4yy64A1kefhXBGZ558aYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-03T00:54:52Z"
    mac: ENC[AES256_GCM,data:jVEA/0a2LEpbsJf3u/H2GMuP8LsGsoMFPTLoXiwNG/p80mX32dbv9Wp0KdsREjiSfKipQT8SwLmtMNyQweBW02VGl4k5KIYSMrY3DHxa4f+omtt04ZN2XxDuFS1EuiHA7rNtj/A9OrXCbZpQK1qpvFY8zYdHJ5VwtAEop8ZCZ9w=,iv:baXu1U/lXkj1uzUjoEEdF9BjsA9h9lzT8nNwwyjKCnY=,tag:qUt6zt8zfYjMo7RCuX2LsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
