---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
  namespace: media
spec:
  storageClassName: media-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SYNOLOGY_IP}
    path: "/volume1/Media"
  mountOptions:
    - nfsvers=3
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs
  resources:
    requests:
      storage: 1Mi
