---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    env:
      # -- Set the container timezone
      TZ: ${TIMEZONE}
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - default
          - networking
          - home-automation
      name: "The Wisesalmon's"
      customApps:
        - name: Synology
          url: http://nas.home.lan:5000
          icon: test-tube
      groups:
        - name: Home Media
          links:
            - name: Radarr
              url: "https://radarr.home.lan"
            - name: Sonarr
              url: "https://radarr.home.lan"
            - name: DVD-Releases
              url: "https://www.dvdsreleasedates.com/"
            - name: Plex
              url: "http://nas.home.lan:32400/web"
            - name: Sabnzbd
              url: "http://192.168.2.30:32770"
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
            - name: Slack
              url: "https://slack.com/signin"
        - name: Cloud
          links:
            - name: Box
              url: "https://box.com"
            - name: Dropbox
              url: "https://dropbox.com"
            - name: Drive
              url: "https://drive.google.com"
        - name: Dev
          links:
            - name: Codepen
              url: "https://codepen.io/"
            - name: Devdocs
              url: "https://devdocs.io"
            - name: Devhints
              url: "https://devhints.io"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            - name: The Verge
              url: "https://theverge.com/"
            - name: MIT Technology Review
              url: "https://www.technologyreview.com/"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
        hosts:
          - host: "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.${SECRET_DOMAIN}"
            secretName: "hajimari-tls"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
